refactor/DEVTOOLING-158 idp_gsuite
MyPureCloud/terraform-provider-genesyscloud pull request #1099
Opened 2024-06-12 19:24 UTC by shrutisuryawanshigenesys

Refactor idp_gsuite into a new package structure

2024-06-17 09:22 UTC, dginty4 requested changes
It looks like you added the attributes `name`, `slo_binding` and `slo_uri` but your not actually using them anywhere. Make sure to be reading and setting these values where needed and add them to the test.

2024-06-17 15:03 UTC, carnellj-genesys approved these changes

2024-06-18 15:26 UTC, charliecon approved these changes
Same here about Declan's comments. Also there are some merge conflicts

2024-06-18 15:26 UTC, charliecon commented on genesyscloud/idp_gsuite/genesyscloud_idp_gsuite_proxy.go
> +	return resp, nil
No need to check the error or add context here (context will be added in the main delete function.) You can just `return resp, err` directly

2024-06-25 09:29 UTC, charliecon approved these changes

2024-06-25 09:30 UTC, merged