Add Caching to resolve slow running exports for knowledge bases
MyPureCloud/terraform-provider-genesyscloud pull request #1402
Opened 2024-12-02 08:52 UTC by HemanthDogiparthi12

2024-12-02 17:13 UTC, charliecon approved these changes

2024-12-02 18:37 UTC, kavinbalagen approved these changes

2024-12-03 13:17 UTC, bbbco requested changes

2024-12-03 13:17 UTC, bbbco commented on genesyscloud/knowledge_label/resource_genesyscloud_knowledge_label_test.go
> +	return fmt.Sprintf(`resource "genesyscloud_knowledge_knowledgebase" "%s" {
Once we refactor `genesyscloud_knowledge_knowledgebase` outside of `gcloud` package we'll be able to reference this function in that package.

2024-12-03 13:17 UTC, bbbco commented on genesyscloud/tfexporter/tf_exporter_resource_test.go
> +	providerResources["genesyscloud_knowledge_label"] = knowledgeLabel.ResourceKnowledgeLabel()
This can become `providerResources[knowledgeLabel.ResourceType] = knowledgeLabel.ResourceKnowledgeLabel()`

2024-12-03 13:17 UTC, bbbco commented on genesyscloud/tfexporter/tf_exporter_resource_test.go
> +	RegisterExporter("genesyscloud_knowledge_label", knowledgeLabel.KnowledgeLabelExporter())
Same here.

2024-12-04 22:37 UTC, bbbco approved these changes
Looks good with  the one other item

2024-12-04 22:37 UTC, bbbco commented on genesyscloud/knowledge_document/genesyscloud_knowledge_document_init_test.go
> +	providerResources["genesyscloud_knowledge_label"] = knowledgeLabel.ResourceKnowledgeLabel()
You can now do `providerResources[knowledgeLabel.ResourceType] = knowledgeLabel.ResourceKnowledgeLabel()`

2024-12-05 11:15 UTC, merged