Outbound Ruleset Package
MyPureCloud/terraform-provider-genesyscloud pull request #560
Opened 2023-06-26 04:46 UTC by HemanthDogiparthi12

2023-06-29 12:11 UTC, carnellj-genesys approved these changes

2023-06-29 14:24 UTC, charliecon approved these changes
Just some merge conflicts that need fixing

2023-07-18 12:49 UTC, carnellj-genesys requested changes

2023-07-18 12:49 UTC, carnellj-genesys commented on genesyscloud/outbound/resource_genesyscloud_outbound_contactlistfilter.go
> +	resources := make(resource_exporter.ResourceIDMetaMap)
No snake_case

2023-07-18 16:42 UTC, charliecon commented on genesyscloud/outbound_ruleset/outbound_ruleset_resource_init_test.go
> +	providerResources["genesyscloud_outbound_contact_list"] = outbound..ResourceOutboundContactList()
Need to remove the `outbound..`

2023-07-20 12:24 UTC, carnellj-genesys approved these changes

2023-07-20 12:28 UTC, merged