<Do Not Merge>DEVTOOLING-337: Refactor Outbound callable timesets
MyPureCloud/terraform-provider-genesyscloud pull request #811
Opened 2024-01-22 13:39 UTC by BrianMoyles

2024-01-22 16:17 UTC, dginty4 commented on genesyscloud/outbound_callabletimeset/resource_genesyscloud_outbound_callabletimeset.go
> +	callableTimeset := platformclientv2.Callabletimeset{
Use `getOutboundCallableTimesetFromResourceData` here like in the update function

2024-01-22 20:03 UTC, carnellj-genesys requested changes

2024-01-22 20:03 UTC, carnellj-genesys commented on genesyscloud/outbound_callabletimeset/data_source_genesyscloud_outbound_callabletimeset.go
>  	outboundAPI := platformclientv2.NewOutboundApiWithConfig(sdkConfig)
Use getOutboundCallabletimesetProxy.  Internally, the getOutboundCallabletimesetProxy uses a singleton to ensure there is only object being returned.

2024-01-22 20:03 UTC, carnellj-genesys commented on genesyscloud/outbound_callabletimeset/resource_genesyscloud_outbound_callabletimeset.go
> +	proxy := newOutboundCallableTimesetProxy(sdkConfig)
Use  getOutboundCallabletimesetProxy instead of the newOutboundCallableTimesetProxy() function

2024-01-22 20:03 UTC, carnellj-genesys commented on genesyscloud/outbound_callabletimeset/resource_genesyscloud_outbound_callabletimeset.go
> +	proxy := newOutboundCallableTimesetProxy(sdkConfig)
Use getOutboundCallabletimesetProxy instead of the newOutboundCallableTimesetProxy() function

2024-01-22 20:03 UTC, carnellj-genesys commented on genesyscloud/outbound_callabletimeset/resource_genesyscloud_outbound_callabletimeset.go
> +	proxy := newOutboundCallableTimesetProxy(sdkConfig)
Use getOutboundCallabletimesetProxy instead of the newOutboundCallableTimesetProxy() function

2024-01-24 16:13 UTC, carnellj-genesys approved these changes

2024-01-24 16:26 UTC, dginty4 approved these changes

2024-01-26 11:32 UTC, charliecon approved these changes

2024-01-26 11:32 UTC, merged