Devtooling-198: Refactored user_roles resource
MyPureCloud/terraform-provider-genesyscloud pull request #832
Opened 2024-01-30 11:18 UTC by BrianMoyles

2024-01-30 11:51 UTC, dginty4 commented on main.go
> +	user_roles.SetRegistrar(regInstance)                    //Registering user roles
should be camelCase

2024-01-30 13:26 UTC, carnellj-genesys requested changes

2024-01-30 13:26 UTC, carnellj-genesys commented on genesyscloud/user_roles/resource_genesyscloud_user_roles.go
> +	authAPI := platformclientv2.NewAuthorizationApiWithConfig(sdkConfig)
Need to extract APi calls out into a Proxy

2024-01-30 14:00 UTC, HemanthDogiparthi12 commented on genesyscloud/user_roles/genesyscloud_user_roles_init_test.go
> +// TestMain is a "setup" function called by the testing framework when run the test
when the test is run

2024-01-30 14:05 UTC, HemanthDogiparthi12 commented on genesyscloud/user_group_role_common.go
> +	RoleAssignmentResource = &schema.Resource{
move this file as well to its own package. most likely this wil be used by users and groups. and add a proxy for this.

2024-02-06 15:53 UTC, carnellj-genesys approved these changes

2024-02-06 16:56 UTC, merged