Devtooling-394: Refactored outbound settings
MyPureCloud/terraform-provider-genesyscloud pull request #850
Opened 2024-02-13 11:49 UTC by BrianMoyles

2024-02-13 15:38 UTC, dginty4 commented on genesyscloud/outbound_settings/genesyscloud_outbound_settings_init_test.go
> +	// TODO: Add references
You can remove this TODO

2024-02-16 07:33 UTC, HemanthDogiparthi12 requested changes

2024-02-16 07:33 UTC, HemanthDogiparthi12 commented on genesyscloud/outbound_settings/resource_genesyscloud_outbound_settings.go
> +	log.Printf("Creating Outbound Setting")
add more meaninful log, else you can remove this as well

2024-02-16 07:33 UTC, HemanthDogiparthi12 commented on genesyscloud/outbound_settings/resource_genesyscloud_outbound_settings.go
> +	d.SetId("settings")
why is this set to hardcoded value

2024-02-16 07:33 UTC, HemanthDogiparthi12 commented on genesyscloud/outbound_settings/resource_genesyscloud_outbound_settings.go
> +		log.Printf("Read Outbound Setting")
same  add more context to the log.  d.id() may be

2024-02-16 07:33 UTC, HemanthDogiparthi12 commented on genesyscloud/outbound_settings/resource_genesyscloud_outbound_settings_schema.go
> +	l.RegisterResource(resourceName, ResourceOutboundSettings())
is there no datasource for this one ?

2024-02-16 10:58 UTC, dginty4 commented
@HemanthDogiparthi12 the answer to most of your comments is due to the fact that outbound settings does not have an id or name property. There is only one outbound settings object in the org and it comes with the org, the cx as code resource just allows the user to configure the settings through terraform

2024-02-16 10:59 UTC, dginty4 approved these changes

2024-02-16 13:43 UTC, HemanthDogiparthi12 approved these changes

2024-02-16 14:50 UTC, merged